#!/data/data/com.termux/files/usr/bin/bash
# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2025 Jonathan D.A. Jewell
#
# install-termux.sh — Install NeuroPhone CLI inside Termux on the phone.
#
# This is the path used when the user wants to drive NeuroPhone from a
# terminal on the device itself, in addition to (or instead of) the APK.
# The APK still owns the home-screen widget; this script gives you the
# `neurophone` CLI.
#
# Run inside Termux:
#   curl -fsSL https://raw.githubusercontent.com/hyperpolymath/neurophone/main/scripts/install-termux.sh -o install-termux.sh
#   bash install-termux.sh
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/share/neurophone}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
MODEL_FILE="llama-3.2-1b-q4_k_m.gguf"
MODEL_URL="https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf"

step() { printf '\n\033[1;36m▶ %s\033[0m\n' "$1"; }
ok()   { printf '\033[1;32m✓\033[0m %s\n' "$1"; }

step "Updating Termux"
pkg update -y
pkg upgrade -y

step "Installing toolchain"
pkg install -y git rust clang cmake make pkg-config openssl libcrypto

step "Cloning NeuroPhone"
mkdir -p "$INSTALL_DIR"
if [ ! -d "$INSTALL_DIR/.git" ]; then
    git clone https://github.com/hyperpolymath/neurophone "$INSTALL_DIR"
else
    git -C "$INSTALL_DIR" pull --ff-only
fi

step "Building neurophone-core (release)"
(cd "$INSTALL_DIR" && cargo build --release -p neurophone-core)

step "Installing CLI shim"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/neurophone" <<EOF
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install-termux.sh
exec "$INSTALL_DIR/target/release/neurophone-core" "\$@"
EOF
chmod +x "$BIN_DIR/neurophone"
ok "neurophone command installed"

step "Downloading model (~700 MB) — skip with NEUROPHONE_NO_MODEL=1"
if [ "${NEUROPHONE_NO_MODEL:-0}" != "1" ]; then
    mkdir -p "$INSTALL_DIR/models"
    if [ ! -f "$INSTALL_DIR/models/$MODEL_FILE" ]; then
        curl -fL --retry 3 -o "$INSTALL_DIR/models/$MODEL_FILE" "$MODEL_URL"
    fi
    ok "Model ready"
fi

step "Default config"
mkdir -p "$HOME/.config/neurophone"
if [ ! -f "$HOME/.config/neurophone/config.toml" ]; then
    cat > "$HOME/.config/neurophone/config.toml" <<EOF
[runtime]
sample_rate_hz = 50.0
local_threshold = 0.7

[llm]
model_path = "$INSTALL_DIR/models/$MODEL_FILE"
n_threads = 4
context_size = 2048

[claude]
# For cloud fallback, set the ANTHROPIC_API_KEY environment variable
# instead of storing a key in this file.
model = "claude-sonnet-4-20250514"
EOF
fi

cat <<EOF

Done. Try:
  neurophone status
  neurophone query "What's happening?"

Add \$BIN_DIR to PATH if it isn't already:
  echo 'export PATH="$BIN_DIR:\$PATH"' >> ~/.bashrc
EOF
