// SPDX-License-Identifier: MPL-2.0
// SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell
//! Codegen: derive the frozen BLE presence wire constants from the vendored
//! `vendor/nearby-presence.a2ml` (burble ADR-0015, wire v1) so the decoder
//! cannot fork the protocol by hand-copying numbers. If the vendored spec is
//! ever re-vendored to a different `wire-version`, the build FAILS LOUDLY here
//! rather than silently miscompiling a v1 decoder against a v2 spec.

use std::path::Path;

fn main() {
    let manifest = "vendor/nearby-presence.a2ml";
    println!("cargo:rerun-if-changed={manifest}");
    println!("cargo:rerun-if-changed=build.rs");

    let text =
        std::fs::read_to_string(manifest).unwrap_or_else(|e| panic!("cannot read {manifest}: {e}"));
    // Strip SPDX license header comments which toml 0.8 cannot parse
    let text_no_spdx = text
        .lines()
        .skip_while(|line| line.trim().starts_with("# SPDX") || line.trim().starts_with("# Copyright") || line.trim().is_empty())
        .collect::<Vec<_>>()
        .join("\n");
    let spec: toml::Value = text_no_spdx
        .parse()
        .unwrap_or_else(|e| panic!("{manifest} is not parseable as TOML/a2ml: {e}"));

    // ── Fail-loud version guard ──────────────────────────────────────────────
    let wire_version = get_int(&spec, "metadata", "wire-version");
    assert_eq!(
        wire_version, 1,
        "vendored {manifest} is wire-version {wire_version}, but this crate \
         implements the v1 presence decoder only. Re-vendoring to a new wire \
         version is a deliberate protocol change: update src/decode.rs and the \
         conformance vectors, then bump this guard. (burble freeze covenant.)"
    );
    let status = get_str(&spec, "metadata", "status");
    assert_eq!(
        status, "frozen",
        "vendored {manifest} status is {status:?}, expected \"frozen\" — only a \
         frozen wire spec may be pinned against."
    );

    // ── Frozen byte layout, taken from the spec (not hand-copied) ────────────
    let magic = get_int(&spec, "presence-frame", "magic");
    let ver_type = get_int(&spec, "presence-frame", "ver_type");
    let magic_offset = get_int(&spec, "presence-frame", "magic-offset");
    let ver_type_offset = get_int(&spec, "presence-frame", "ver_type-offset");
    let epoch_offset = get_int(&spec, "presence-frame", "epoch-offset");
    let epoch_bytes = get_int(&spec, "presence-frame", "epoch-bytes");
    let beacon_id_offset = get_int(&spec, "presence-frame", "beacon_id-offset");
    let beacon_id_bytes = get_int(&spec, "presence-frame", "beacon_id-bytes");
    let epoch_seconds = get_int(&spec, "rotation", "period-seconds");
    let accept_epoch_window = get_int(&spec, "resolution", "accept-epoch-window");

    // Frame length is the envelope (magic + ver_type + epoch) plus the beacon id.
    let frame_bytes = beacon_id_offset + beacon_id_bytes;

    // Sanity: epoch must be a u32 (the decoder reads it as u32 BE).
    assert_eq!(
        epoch_bytes, 4,
        "presence-frame epoch-bytes must be 4 (u32 BE)"
    );

    let generated = format!(
        "// @generated by build.rs from vendor/nearby-presence.a2ml — do not edit.\n\
         // Frozen BLE presence wire constants (burble ADR-0015, wire v{wire_version}).\n\
         /// BLE Manufacturer-Specific-Data company id the beacon advertises under.\n\
         pub const COMPANY_ID: u16 = 0xFFFF;\n\
         /// Frame byte 0 — protocol magic.\n\
         pub const MAGIC: u8 = {magic:#04x};\n\
         /// Frame byte 1 — (wire_version << 4) | frame_type; presence = 0x12.\n\
         pub const VER_TYPE: u8 = {ver_type:#04x};\n\
         pub const MAGIC_OFFSET: usize = {magic_offset};\n\
         pub const VER_TYPE_OFFSET: usize = {ver_type_offset};\n\
         pub const EPOCH_OFFSET: usize = {epoch_offset};\n\
         pub const EPOCH_BYTES: usize = {epoch_bytes};\n\
         pub const BEACON_ID_OFFSET: usize = {beacon_id_offset};\n\
         /// HMAC-SHA256 truncation length for the contact-resolvable beacon id.\n\
         pub const BEACON_ID_BYTES: usize = {beacon_id_bytes};\n\
         /// Total presence-frame length in bytes.\n\
         pub const FRAME_BYTES: usize = {frame_bytes};\n\
         /// Beacon rotation period; epoch = unix_seconds / EPOCH_SECONDS.\n\
         pub const EPOCH_SECONDS: u64 = {epoch_seconds};\n\
         /// Accepted |carried_epoch - epoch(now)| when resolving.\n\
         pub const ACCEPT_EPOCH_WINDOW: u64 = {accept_epoch_window};\n\
         /// HMAC-SHA256 domain-separation label for the presence beacon id.\n\
         pub const LABEL_PRES: &[u8] = b\"BRBL-PRES-v1\";\n\
         /// Vendored spec wire version this decoder was generated against.\n\
         pub const WIRE_VERSION: u8 = {wire_version};\n"
    );

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("wire.rs");
    std::fs::write(&dest, generated).expect("cannot write generated wire.rs");
}

fn section<'a>(spec: &'a toml::Value, sect: &str) -> &'a toml::value::Table {
    spec.get(sect)
        .and_then(|v| v.as_table())
        .unwrap_or_else(|| panic!("nearby-presence.a2ml: missing [{sect}] section"))
}

fn get_int(spec: &toml::Value, sect: &str, key: &str) -> i64 {
    section(spec, sect)
        .get(key)
        .and_then(|v| v.as_integer())
        .unwrap_or_else(|| panic!("nearby-presence.a2ml: [{sect}].{key} missing or not an integer"))
}

fn get_str(spec: &toml::Value, sect: &str, key: &str) -> String {
    section(spec, sect)
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("nearby-presence.a2ml: [{sect}].{key} missing or not a string"))
        .to_string()
}
